name: Notice Scraper

on:
  schedule:
    - cron: '15 4 * * *'   # 10:00 AM NPT
    - cron: '15 7 * * *'   # 1:00  PM NPT
    - cron: '15 11 * * *'  # 5:00  PM NPT
  workflow_dispatch: {}     # manual run button

permissions:
  contents: write           # allow committing seen_notices.json

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for commits)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python scraper.py

      - name: Commit & push state if changed
        run: |
          if ! git diff --quiet -- seen_notices.json 2>/dev/null; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add seen_notices.json
            git commit -m "chore: update seen_notices.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
